const QUESTIONS = [
    // =============================================================================
    // 1. 학교에서 (School) - 10 Questions
    // =============================================================================
    { category: "School", difficulty: 1, ko: "선생님, 질문 있어요.", en: "Teacher, I have a question.", vn: "Thưa thầy, em có câu hỏi.", cn: "老师，我有一个问题。", th: "คุณครูคะ/ครับ มีคำถามครับ/ค่ะ", ph: "Guro, may tanong ako.", id: "Guru, saya ada pertanyaan.", mn: "Багшаа, асуулт байна.", uz: "O'qituvchi, menda savol bor.", ne: "शिक्षक, मसँग एउटा प्रश्न छ।", km: "លោកគ្រូ ខ្ញុំមានសំណួរ។", si: "ගුරුතුමනි, මට ප්‍රශ්නයක් තියෙනවා.", my: "ဆရာ/ဆရာမ၊ ကျွန်တော့်မှာ မေးခွန်းရှိပါတယ်။", bn: "শিক্ষক, আমার একটা প্রশ্ন আছে।", lo: "ອາຈານ, ຂ້ອຍມີຄໍາຖາມ.", ru: "Учитель, у меня вопрос.", jp: "先生、質問があります。", kz: "Мұғалім, менде сұрақ бар." },
    { category: "School", difficulty: 2, ko: "다시 한번 설명해 주세요.", en: "Please explain it again.", vn: "Xin giải thích lại lần nữa.", cn: "请再解释一遍。", th: "ช่วยอธิบายอีกครั้งได้ไหมครับ/คะ", ph: "Paki-paliwanag ulit.", id: "Tolong jelaskan sekali lagi.", mn: "Дахиад нэг тайлбарлаж өгнө үү.", uz: "Iltimos, yana bir bor tushuntirib bering.", ne: "कृपया फेरि बुझाउनुहोस्।", km: "សូមពន្យល់ម្តងទៀត។", si: "කරුණාකර එය නැවත පැහැදිලි කරන්න.", my: "ကျေးဇူးပြုပြီး နောက်တစ်ခေါက် ရှင်းပြပေးပါ။", bn: "দয়া করে আবার ব্যাখ্যা করুন।", lo: "ກະລຸນາອະທິບາຍອີກເທື່ອໜຶ່ງ.", ru: "Пожалуйста, объясните еще раз.", jp: "もう一度説明してください。", kz: "Тағы бір рет түсіндіріп жіберіңізші." },
    { category: "School", difficulty: 1, ko: "화장실 다녀와도 될까요?", en: "May I go to the bathroom?", vn: "Em có thể đi vệ sinh được không?", cn: "我可以去洗手间吗？", th: "ขออนุญาตไปห้องน้ำได้ไหมครับ/คะ", ph: "Pwede ba akong pumunta sa banyo?", id: "Bolehkah saya pergi ke toilet?", mn: "Би бие засаад ирж болох уу?", uz: "Hojatxonaga chiqsamm maylimi?", ne: "के म शौचालय जान सक्छु?", km: "តើខ្ញុំអាចទៅបន្ទប់ទឹកបានទេ?", si: "මට වැසිකිළියට යන්න පුළුවන්ද?", my: "အိမ်သာသွားလို့ရမလား။", bn: "আমি কি বাথরুমে যেতে পারি?", lo: "ຂ້ອຍຂໍໄປຫ້ອງນ້ຳໄດ້ບໍ?", ru: "Можно выйти в туалет?", jp: "トイレに行ってもいいですか？", kz: "Дәретханаға баруға бола ма?" },
    { category: "School", difficulty: 1, ko: "한국어를 배우고 싶어요.", en: "I want to learn Korean.", vn: "Tôi muốn học tiếng Hàn.", cn: "我想学韩语。", th: "ฉันอยากเรียนภาษาเกาหลีครับ/ค่ะ", ph: "Gusto kong matuto ng Korean.", id: "Saya ingin belajar bahasa Korea.", mn: "Би Солонгос хэл сурмаар байна.", uz: "Men koreys tilini o'rganmoqchiman.", ne: "म कोरियाली भाषा सिक्न चाहन्छु।", km: "ខ្ញុំចង់រៀនភាសាកូរ៉េ។", si: "මට කොරියානු භාෂාව ඉගෙන ගන්න ඕන.", my: "ကျွန်တော် ကိုရီးယားစကား သင်ချင်ပါတယ်။", bn: "আমি কোরিয়ান ভাষা শিখতে চাই।", lo: "ຂ້ອຍຢາກຮຽນພາສາເກົາຫຼີ.", ru: "Я хочу выучить корейский.", jp: "韓国語を習いたいです。", kz: "Мен кәріс тілін үйренгім келеді." },
    { category: "School", difficulty: 1, ko: "천천히 말해 주세요.", en: "Please speak slowly.", vn: "Xin hãy nói chậm lại.", cn: "请慢一点说。", th: "ช่วยพูดช้าๆ หน่อยได้ไหมครับ/คะ", ph: "Pakibagalan ang pagsasalita.", id: "Tolong bicara pelan-pelan.", mn: "Удаан ярина уу.", uz: "Iltimos, sekinroq gapiring.", ne: "कृपया बिस्तारै बोल्नुहोस्।", km: "សូមនិយាយយឺតៗ។", si: "කරුණාකර සෙමින් කතා කරන්න.", my: "ကျေးဇူးပြုပြီး ဖြည်းဖြည်းပြောပါ။", bn: "দয়া করে ধীরে কথা বলুন।", lo: "ກະລຸນາເວົ້າຊ້າໆ.", ru: "Пожалуйста, говорите медленнее.", jp: "もっとゆっくり話してください。", kz: "Баяу сөйлеңізші." },
    { category: "School", difficulty: 1, ko: "몇 페이지예요?", en: "What page is it?", vn: "Trang mấy vậy ạ?", cn: "是哪一页？", th: "หน้าไหนครับ/คะ", ph: "Anong pahina?", id: "Halaman berapa?", mn: "Хэддүгээр хуудас вэ?", uz: "Qaysi sahifa?", ne: "कति पृष्ठ हो?", km: "តើទំព័រទីប៉ុន្មាន?", si: "පිටුව කීයද?", my: "ဘယ်စာမျက်နှာလဲ။", bn: "কত পাতা?", lo: "ໜ້າໃດ?", ru: "Какая это страница?", jp: "何ページですか？", kz: "Қай бет?" },
    { category: "School", difficulty: 1, ko: "숙제를 잊어버렸어요.", en: "I forgot my homework.", vn: "Em quên làm bài tập rồi.", cn: "我忘记带作业了。", th: "ฉันลืมทำการบ้านครับ/ค่ะ", ph: "Nakalimutan ko ang assignment ko.", id: "Saya lupa PR saya.", mn: "Би гэрийн даалгавраа мартчихсан.", uz: "Uy vazifasini unutib qo'ydim.", ne: "मैले गृहकार्य बिर्सें।", km: "ខ្ញុំភ្លេចលំហាត់របស់ខ្ញុំ។", si: "මට ගෙදර වැඩ අමතක වුණා.", my: "အိမ်စာမေ့သွားတယ်။", bn: "আমি বাড়ির কাজ ভুলে গেছি।", lo: "ຂ້ອຍລືມວຽກບ້ານ.", ru: "Я забыл домашнее задание.", jp: "宿題を忘れました。", kz: "Мен үй тапсырмасын ұмытып кеттім." },
    { category: "School", difficulty: 1, ko: "연필 좀 빌려주세요.", en: "Can I borrow a pencil?", vn: "Cho mình mượn bút chì với.", cn: "能借我一支铅笔吗？", th: "ขอยืมดินสอหน่อยได้ไหมครับ/คะ", ph: "Pwede bang humiram ng lapis?", id: "Bolehkah saya meminjam pensil?", mn: "Харандаа зээлж болох уу?", uz: "Qalam olib tursam maylimi?", ne: "के म सिसाकलम सापटी लिन सक्छु?", km: "តើខ្ញុំអាចខ្ចីខ្មៅដៃបានទេ?", si: "මට පැන්සලක් ණයට ගන්න පුළුවන්ද?", my: "ခဲတံငှားလို့ရမလား။", bn: "আমি কি একটি পেন্সিল ধার করতে পারি?", lo: "ຂ້ອຍຂໍຢືມສໍດຳໄດ້ບໍ່?", ru: "Можно одолжить карандаш?", jp: "鉛筆を借りてもいいですか？", kz: "Қалам алып тұрсам бола ма?" },
    { category: "School", difficulty: 2, ko: "시험이 언제예요?", en: "When is the exam?", vn: "Khi nào thi vậy?", cn: "什么时候考试？", th: "สอบเมื่อไหร่ครับ/คะ", ph: "Kailan ang exam?", id: "Kapan ujiannya?", mn: "Шалгалт хэзээ вэ?", uz: "Imtihon qachon?", ne: "परीक्षा कहिले छ?", km: "តើការប្រឡងនៅពេលណា?", si: "විභාගය කවදාද?", my: "စာမေးပွဲ ဘယ်တော့လဲ။", bn: "পরীক্ষা কবে?", lo: "ສອບເສັງມື້ໃດ?", ru: "Когда экзамен?", jp: "試験はいつですか？", kz: "Емтихан қашан?" },
    { category: "School", difficulty: 1, ko: "감사합니다, 선생님.", en: "Thank you, Teacher.", vn: "Em cảm ơn thầy/cô.", cn: "谢谢老师。", th: "ขอบคุณครับ/ค่ะ คุณครู", ph: "Salamat po, Guro.", id: "Terima kasih, Guru.", mn: "Баярлалаа, багшаа.", uz: "Rahmat, ustoz.", ne: "धन्यवाद, शिक्षक।", km: "សូមអរគុណ លោកគ្រូ។", si: "ස්තූතියි, ගුරුතුමනි.", my: "ကျေးဇူးတင်ပါတယ် ဆရာ/ဆရာမ။", bn: "ধন্যবাদ, শিক্ষক।", lo: "ຂອບໃຈ, ອາຈານ.", ru: "Спасибо, учитель.", jp: "ありがとうございます、先生。", kz: "Рахмет, мұғалім." },

    // =============================================================================
    // 2. 여행에서 (Travel) - 10 Questions
    // =============================================================================
    { category: "Travel", difficulty: 1, ko: "예약 확인해 주세요.", en: "I have a reservation.", vn: "Tôi đã đặt trước.", cn: "我有预订。", th: "ฉันจองไว้แล้วครับ/ค่ะ", ph: "May reservation ako.", id: "Saya sudah reservasi.", mn: "Би захиалга өгсөн.", uz: "Menda bron bor.", ne: "मसँग आरक्षण छ।", km: "ខ្ញុំបានកក់ទុកហើយ។", si: "මට වෙන් කිරීමක් තිබේ.", my: "ကျွန်တော့်မှာ ကြိုတင်မှာကြားထားတာ ရှိပါတယ်။", bn: "আমার রিজার্ভেশন আছে।", lo: "ຂ້ອຍໄດ້ຈອງແລ້ວ.", ru: "У меня забронировано.", jp: "予約しています。", kz: "Менде бронь бар." },
    { category: "Travel", difficulty: 1, ko: "빈 방 있나요?", en: "Do you have a vacant room?", vn: "Có phòng trống không?", cn: "有空房吗？", th: "มีห้องว่างไหมครับ/คะ", ph: "May bakanteng kwarto ba?", id: "Apakah ada kamar kosong?", mn: "Сул өрөө байна уу?", uz: "Bo'sh xona bormi?", ne: "के त्यहाँ खाली कोठा छ?", km: "តើមានបន្ទប់ទំនេរទេ?", si: "හිස් කාමරයක් තිබේද?", my: "အခန်းလွတ် ရှိပါသလား။", bn: "আপনার কি খালি রুম আছে?", lo: "ມີຫ້ອງຫວ່າງບໍ?", ru: "У вас есть свободные номера?", jp: "空いている部屋はありますか？", kz: "Бос бөлме бар ма?" },
    { category: "Travel", difficulty: 2, ko: "와이파이 비밀번호가 뭐예요?", en: "What is the WiFi password?", vn: "Mật khẩu WiFi là gì?", cn: "WiFi密码是多少？", th: "รหัสผ่าน WiFi คืออะไรครับ/คะ", ph: "Ano ang password ng WiFi?", id: "Apa kata sandi WiFi-nya?", mn: "WiFi нууц үг юу вэ?", uz: "Wi-Fi paroli nima?", ne: "WiFi पासवर्ड के हो?", km: "តើលេខសម្ងាត់ WiFi គឺជាអ្វី?", si: "WiFi මුරපදය මොකක්ද?", my: "WiFi စကားဝှက်က ဘာလဲ။", bn: "WiFi পাসওয়ার্ড কি?", lo: "ລະຫັດ WiFi ແມ່ນຫຍັງ?", ru: "Какой пароль от Wi-Fi?", jp: "Wi-Fiのパスワードは何ですか？", kz: "Wi-Fi құпия сөзі қандай?" },
    { category: "Travel", difficulty: 1, ko: "택시를 불러주세요.", en: "Please call a taxi.", vn: "Làm ơn gọi giúp tôi taxi.", cn: "请帮我叫辆出租车。", th: "ช่วยเรียกแท็กซี่ให้หน่อยครับ/ค่ะ", ph: "Pakitawag ng taxi.", id: "Tolong panggilkan taksi.", mn: "Такси дуудаад өгөөч.", uz: "Iltimos, taksi chaqirib bering.", ne: "कृपया ट्याक्सी बोलाउनुहोस्।", km: "សូមហៅតាក់ស៊ី។", si: "කරුණාකර ටැක්සියක් අමතන්න.", my: "ကျေးဇူးပြုပြီး တက္ကစီ ခေါ်ပေးပါ။", bn: "দয়া করে একটি ট্যাক্সি ডাকুন।", lo: "ກະລຸນາເອີ້ນແທັກຊີໃຫ້ແດ່.", ru: "Пожалуйста, вызовите такси.", jp: "タクシーを呼んでください。", kz: "Такси шақырып жіберіңізші." },
    { category: "Travel", difficulty: 2, ko: "지하철역이 어디예요?", en: "Where is the subway station?", vn: "Ga tàu điện ngầm ở đâu?", cn: "地铁站在哪里？", th: "สถานีรถไฟใต้ดินอยู่ที่ไหนครับ/ค่ะ", ph: "Saan ang istasyon ng subway?", id: "Di mana stasiun kereta bawah tanah?", mn: "Метроны буудал хаана вэ?", uz: "Metro bekati qayerda?", ne: "सबवे स्टेशन कहाँ छ?", km: "តើស្ថានីយ៍រថភ្លើងក្រោមដីនៅឯណា?", si: "උමං දුම්රිය ස්ථානය කොහෙද?", my: "မြေအောက်ရထားဘူတာ ဘယ်မှာလဲ။", bn: "সাবওয়ে স্টেশন কোথায়?", lo: "ສະຖານີລົດໄຟໃຕ້ດິນຢູ່ໃສ?", ru: "Где станция метро?", jp: "地下鉄の駅はどこですか？", kz: "Метро бекеті қай жерде?" },
    { category: "Travel", difficulty: 2, ko: "이 주소로 가주세요.", en: "Take me to this address.", vn: "Làm ơn đưa tôi đến địa chỉ này.", cn: "请带我去这个地址。", th: "ไปส่งที่ที่อยู่นี้หน่อยครับ/ค่ะ", ph: "Dalhin mo ako sa address na ito.", id: "Antar saya ke alamat ini.", mn: "Намайг энэ хаяг руу хүргэж өгөөч.", uz: "Meni shu manzilga olib boring.", ne: "मलाई यो ठेगानामा लैजानुहोस्।", km: "សូមនាំខ្ញុំទៅអាសយដ្ឋាននេះ។", si: "මාව මේ ලිපිනයට ගෙනියන්න.", my: "ဒီလိပ်စာကို ပို့ပေးပါ။", bn: "আমাকে এই ঠিকানায় নিয়ে যান।", lo: "ພາຂ້ອຍໄປທີ່ຢູ່.", ru: "Отвезите меня по этому адресу.", jp: "この住所へ行ってください。", kz: "Мені осы мекенжайға апарыңызшы." },
    { category: "Travel", difficulty: 2, ko: "얼마나 걸려요?", en: "How long does it take?", vn: "Mất bao lâu?", cn: "需要多长时间？", th: "ใช้เวลานานเท่าไหร่ครับ/ค่ะ", ph: "Gaano katagal?", id: "Berapa lama?", mn: "Хэр удах вэ?", uz: "Qancha vaqt ketadi?", ne: "कति समय लाग्छ?", km: "តើត្រូវចំណាយពេលប៉ុន្មាន?", si: "කොපමණ වෙලාවක් යනවද?", my: "ဘယ်လောက်ကြာမလဲ။", bn: "কতক্ষণ লাগবে?", lo: "ໃຊ້​ເວ​ລາ​ດົນ​ປານ​ໃດ?", ru: "Сколько времени это займет?", jp: "どのくらいかかりますか？", kz: "Қанша уақыт алады?" },
    { category: "Travel", difficulty: 1, ko: "사진 좀 찍어주세요.", en: "Please take a picture of me.", vn: "Chụp giúp tôi tấm ảnh với.", cn: "请帮我拍张照。", th: "ช่วยถ่ายรูปให้หน่อยได้ไหมครับ/ค่ะ", ph: "Pwede bang pa-picture?", id: "Tolong ambilkan foto.", mn: "Зураг дараад өгөөч.", uz: "Rasmga olib qo'ying.", ne: "कृपया मेरो फोटो खिच्नुहोस्।", km: "សូមថតរូបឱ្យខ្ញុំ។", si: "කරුණාකර මගේ පින්තූරයක් ගන්න.", my: "ဓာတ်ပုံရိုက်ပေးပါ။", bn: "দয়া করে আমার একটি ছবি তুলুন।", lo: "ກະລຸນາຖ່າຍຮູບໃຫ້ແດ່.", ru: "Сфотографируйте меня, пожалуйста.", jp: "写真を撮ってください。", kz: "Суретке түсіріп жіберіңізші." },
    { category: "Travel", difficulty: 1, ko: "여기가 정말 아름다워요.", en: "It is beautiful here.", vn: "Ở đây đẹp quá.", cn: "这里真漂亮。", th: "ที่นี่สวยมากครับ/ค่ะ", ph: "Ang ganda dito.", id: "Di sini indah sekali.", mn: "Энд үнэхээр гоё юм.", uz: "Bu yer juda chiroyli.", ne: "यहाँ धेरै सुन्दर छ।", km: "ទីនេះស្អាតណាស់។", si: "මෙතන හරිම ලස්සනයි.", my: "ဒီနေရာက တကယ်လှတယ်။", bn: "এখানে খুব সুন্দর।", lo: "ຢູ່ນີ້ງາມຫຼາຍ.", ru: "Здесь очень красиво.", jp: "ここは本当に美しいです。", kz: "Бұл жер өте әдемі." },
    { category: "Travel", difficulty: 1, ko: "지도 좀 얻을 수 있을까요?", en: "Can I get a map?", vn: "Cho tôi xin bản đồ được không?", cn: "能给我一份地图吗？", th: "ขอแผนที่หน่อยได้ไหมครับ/ค่ะ", ph: "Pwede bang makahingi ng mapa?", id: "Bisa minta peta?", mn: "Газрын зураг авч болох уу?", uz: "Xarita olsam bo'ladimi?", ne: "के म नक्सा पाउन सक्छु?", km: "តើខ្ញុំអាចសុំផែនទីបានទេ?", si: "මට සිතියමක් ලබා ගත හැකිද?", my: "မြေပုံရနိုင်မလား။", bn: "আমি কি একটি মানচিত্র পেতে পারি?", lo: "ຂໍແຜນທີ່ແດ່ໄດ້ບໍ່?", ru: "Можно мне карту?", jp: "地図をもらえますか？", kz: "Карта алсам бола ма?" },
